// Generates margin/css/tokens.css and margin/tokens/contrast.md from margin/tokens/tokens.json.
// Run with `npm run margin:tokens`. Never hand-edit the generated files.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const t = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));

const lines = [];
const out = (s = '') => lines.push(s);

out('/* Margin tokens, GENERATED from tokens/tokens.json by scripts/build-tokens.mjs. Do not edit. */');
out(':root {');
for (const [k, v] of Object.entries(t.color)) out(`  --m-${k}: ${v.value};`);
out();
for (const [k, v] of Object.entries(t.font)) out(`  --m-font-${k}: ${v.value};`);
out();
for (const [k, v] of Object.entries(t.type)) {
  out(`  --m-${k}-size: ${v.size};`);
  out(`  --m-${k}-leading: ${v.leading};`);
}
out();
for (const [k, v] of Object.entries(t.page)) {
  if (k === 'basis') continue;
  out(`  --m-page-${k}: ${v};`);
}
out();
for (const [k, v] of Object.entries(t.rhythm)) out(`  --m-rhythm-${k}: ${v.value};`);
out();
out(`  --m-space-unit: ${t.space.unit};`);
for (const [k, v] of Object.entries(t.space.scale)) out(`  --m-space-${k}: ${v};`);
out();
for (const [k, v] of Object.entries(t.route)) out(`  --m-route-${k}: ${v.value};`);
out();
for (const [k, v] of Object.entries(t.motion)) {
  out(`  --m-motion-${k}: ${v.value};`);
  if (v.easing) out(`  --m-motion-${k}-easing: ${v.easing};`);
}
out('}');
out();
out('/* Type styles: one class per role. */');
for (const [k, v] of Object.entries(t.type)) {
  out(`.m-${k} {`);
  out(`  font-family: var(--m-font-${v.family});`);
  out(`  font-size: var(--m-${k}-size);`);
  out(`  line-height: var(--m-${k}-leading);`);
  out(`  font-weight: ${v.weight};`);
  if (v.style) out(`  font-style: ${v.style};`);
  out(`  letter-spacing: ${v.tracking};`);
  if (v.case === 'upper') out('  text-transform: uppercase;');
  out(`  color: var(--m-${v.color});`);
  out('}');
}
writeFileSync(join(root, 'css/tokens.css'), lines.join('\n') + '\n');

// WCAG 2.x contrast of every colour against both grounds.
const lum = (hex) => {
  const c = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((x) => (x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => {
  const [x, y] = [lum(a), lum(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
};
const verdict = (r) => (r >= 7 ? 'AAA' : r >= 4.5 ? 'AA' : r >= 3 ? 'AA large only' : 'Fails for text');
const md = [
  '# Margin, contrast',
  '',
  'GENERATED by `scripts/build-tokens.mjs` from `tokens/tokens.json`. WCAG 2.x ratios.',
  '',
  '| Colour | Hex | on paper | on paper-deep |',
  '|---|---|---|---|',
];
for (const k of ['ink', 'blue', 'route', 'mustard']) {
  const hex = t.color[k].value;
  const a = ratio(hex, t.color.paper.value);
  const b = ratio(hex, t.color['paper-deep'].value);
  md.push(`| ${k} | \`${hex}\` | ${a.toFixed(2)}, ${verdict(a)} | ${b.toFixed(2)}, ${verdict(b)} |`);
}
writeFileSync(join(root, 'tokens/contrast.md'), md.join('\n') + '\n');
console.log(md.slice(4).join('\n'));
